#!/bin/bash
#SBATCH -N 1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=60:00:00
#SBATCH --mem=16GB
#SBATCH --job-name=test
#SBATCH --output=test_job_%j.out

# hidden_dim = int(2**np.random.uniform(6, 9))
# l2_regularizer_weight = 10**np.random.uniform(-2, -5)
# lr = 10**np.random.uniform(-2.5, -3.5)
# penalty_anneal_iters = np.random.randint(50, 250)
# penalty_weight = 10**np.random.uniform(2, 6)
echo "IRM (ours):"
python3 -u ./code/colored_mnist/hold_out_main.py \
  --hidden_dim=390 \
  --l2_regularizer_weight=0.00110794568 \
  --lr=0.0004898536566546834 \
  --penalty_anneal_iters=190 \
  --penalty_weight=91257.18613115903 \
  --steps=501 \
  --n_restarts 1 \
  -b=25000 \
  --sigma=8.0 \
  --exper_name=8irm