#!/bin/bash
#SBATCH -N 1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=60:00:00
#SBATCH --mem=16GB
#SBATCH --job-name=test
#SBATCH --output=test_job_%j.out

# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

# IRM (the main result). These hyperparameters were chosen by random search
# with 50 trials and the following ranges. We picked the values which maximized
# min(train_env0_acc, train_env1_acc, test_acc).  We also chose the steps
# hyperparameter by exhaustive search over [101, 201, 301, 401, 501].
#
# hidden_dim = int(2**np.random.uniform(6, 9))
# l2_regularizer_weight = 10**np.random.uniform(-2, -5)
# lr = 10**np.random.uniform(-2.5, -3.5)
# penalty_anneal_iters = np.random.randint(50, 250)
# penalty_weight = 10**np.random.uniform(2, 6)
#echo "IRM (ours):"
#python3 -u ./code/colored_mnist/main.py \
#  --hidden_dim=390 \
#  --l2_regularizer_weight=0.00110794568 \
#  --lr=0.0004898536566546834 \
#  --penalty_anneal_iters=190 \
#  --penalty_weight=91257.18613115903 \
#  --steps=501

echo "Invar Penalty"
python3 -u ./code/colored_mnist/main.py \
  --hidden_dim=390 \
  --l2_regularizer_weight=0.000001 \
  --lr=0.0004898536566546834 \
  --penalty_anneal_iters=0 \
  --penalty_weight=100000.0 \
  --new_invar_penalty \
  --invar_penalty \
  --steps=501 \
  -b=5000 \
  --n_restarts 1 \
  --sigma=0.1 \
  --exper_name=new_sig_0_1_invar_penalty

